name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_core: ^2.24.2
  modal_progress_hud_nsn: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
