// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB71ne825HN5PNzs6SyD-93_jI19PFIEW0',
    appId: '1:526553714703:web:abc55fca204cddc4c6d37a',
    messagingSenderId: '526553714703',
    projectId: 'flash-chat-2a243',
    authDomain: 'flash-chat-2a243.firebaseapp.com',
    storageBucket: 'flash-chat-2a243.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3HABSssPuO45Mr1VFUapLFr9673dSTE',
    appId: '1:526553714703:android:b4a0fa1978273d38c6d37a',
    messagingSenderId: '526553714703',
    projectId: 'flash-chat-2a243',
    storageBucket: 'flash-chat-2a243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPNfk83oXsUoylasre8T1VWggg8jCr3Y',
    appId: '1:526553714703:ios:d8d882ac4ed0811fc6d37a',
    messagingSenderId: '526553714703',
    projectId: 'flash-chat-2a243',
    storageBucket: 'flash-chat-2a243.appspot.com',
    iosBundleId: 'com.ikramzargar.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPNfk83oXsUoylasre8T1VWggg8jCr3Y',
    appId: '1:526553714703:ios:e4e107e7c6eb1b1dc6d37a',
    messagingSenderId: '526553714703',
    projectId: 'flash-chat-2a243',
    storageBucket: 'flash-chat-2a243.appspot.com',
    iosBundleId: 'com.ikramzargar.flashChat.RunnerTests',
  );
}
